# Generated by Django 3.2.9 on 2021-11-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='people',
        ),
        migrations.AddField(
            model_name='tweet',
            name='people',
            field=models.JSONField(default=list),
        ),
    ]
