# Generated by Django 3.2.9 on 2021-12-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(default='', max_length=279),
        ),
    ]
